/**

	@class UserEventUnpacking

*/

#ifndef USEREVENTUNPACKING_H
#define USEREVENTUNPACKING_H

#include <TGo4EventElement.h> // mother class

class TClonesArray;

class UserEventUnpacking : public TGo4EventElement
{
	friend class UserProcUnpacking; // provider
	friend class UserProcMonitoring; // consumer
	friend class UserProcStep2; // consumer

public:
	UserEventUnpacking(const char* name = "UserEventUnpacking");
	virtual ~UserEventUnpacking();

	void Clear(Option_t* t = "");

private:

	/**
	 * One message is, in essence, a pair (ch,val).
	 * This data is accompanied by lots of other
	 * values from the event header, subevent header,
	 * subsbevent header and footer, etc.
	 * See data/RawMessage.h
	 */
	TClonesArray* mRawMessages;

	/**
	 * Data from CAMAC as if generated by the MWPCs.
	 * H - header, F - footer, X - used half-byte.
	 * last 2 bytes are extracted from the raw data into mCAMAC
	 * HHHHHHHH
	 * 0000XXXX - mCAMAC[0]
	 * 0000XXXX - mCAMAC[1]
	 * FFFFFFFF
	 * HHHHHHHH
	 * 0000XXXX - mCAMAC[2]
	 * 0000XXXX - mCAMAC[3]
	 * FFFFFFFF
	 * HHHHHHHH
	 * 0000XXXX - mCAMAC[4]
	 * 0000XXXX - mCAMAC[5]
	 * FFFFFFFF
	 * HHHHHHHH
	 * 0000XXXX - mCAMAC[6]
	 * 0000XXXX - mCAMAC[7]
	 * FFFFFFFF
	 */
	UShort_t mCAMAC[8];

	ClassDef(UserEventUnpacking, 1);
};

#endif // USEREVENTUNPACKING_H
